### ISSUE TITLE
nxos_ping error in format with python 2.6

### ISSUE THREAD

**Issue by EvgeniyV** [jedelman8/nxos-ansible#50]
Hi
I am using Ansible 1.9 on centos 6.7 with python 2.6
I get error in task with nxos_ping:

```
TASK: [ping host] ************************************************************* 
failed: [10.10.30.1] => (item=10.10.30.6) => {"failed": true, "item": "10.10.30.6", "parsed": false}
Traceback (most recent call last):
  File "/home/yvarfolo/.ansible/tmp/ansible-tmp-1452676240.88-100692330905793/nxos_ping", line 1834, in <module>
    main()
  File "/home/yvarfolo/.ansible/tmp/ansible-tmp-1452676240.88-100692330905793/nxos_ping", line 195, in main
    ping_string += ' {} {}'.format(command, arg)
ValueError: zero length field name in format
```

as i understand for comparability with python 2.6 better to write:

```
ping_string += ' {0} {1}'.format(command, arg)
```

it would be more flexible and also comfortable with python 2.7

**Comment by jedelman8** [comment]
You're right. We've gradually fixed a few of these already. Will get this fixed ASAP.

**Comment by jedelman8** [comment]
This has been fixed.  Thanks.
