### ISSUE TITLE
Cant create vpc

### ISSUE THREAD

**Issue by EvgeniyV** [jedelman8/nxos-ansible#66]
Hi!
I'm working with: Cisco Nexus5548 Chassis,System version: 7.2(1)N1(1), BIOS: version 3.6.0
I am trying to create  VPC:

```
      - name: configure vps 100
        nxos_vpc: host={{ inventory_hostname }} 
                 domain=233 role_priority=1000 system_priority=2000 pkl_src=192.168.100.1 pkl_dest=192.168.100.2
```

but get exception:

```
Traceback (most recent call last):
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1453820353.9-192663310558892/nxos_vpc", line 1901, in <module>
    main()
  File "/home/varfolomeiev/.ansible/tmp/ansible-tmp-1453820353.9-192663310558892/nxos_vpc", line 237, in main
    if not nxapi_lib.feature_enabled(device, 'vpc'):
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 1960, in feature_enabled
    data = device.show(command)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/device.py", line 108, in show
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature Name          Instance  State   
--------------------  --------  --------
bfd                   1         disabled
bfd_app               1         disabled
....
udld                  1         enabled 
vni                   1         disabled
vnseg_vlan            1         disabled
vpc                   1         enabled 
vrrp                  1         disabled
vrrpv3                1         disabled
vtp                   1         enabled 
wccp                  1         disabled. Structured output unsupported. Error Found on Command Number: 1
```

**Comment by jedelman8** [comment]
Yeah, there are some errors on the 3K/5K/7K on checking features.  

You can comment out or remove these lines in the module for now:

```
  if not nxapi_lib.feature_enabled(device, 'vpc'):
        module.fail_json(msg='VPC feature needs to be enabled first')

```

**Comment by jedelman8** [comment]
Let me know after you try.

**Comment by jedelman8** [comment]
Ever try this?

**Comment by EvgeniyV** [comment]
Yes -  it works but now i have troubles  with logical part  - nexus returns configure error when i am setting fake  params `pkl_src=192.168.100.1 pkl_dest=192.168.100.2`.
So when i will check it with real parameters i think it will work fine.
thanks!
