### ISSUE TITLE
 nxos_get_facts: detail undefined and cannot be passed

### ISSUE THREAD

**Issue by jean-christophe-manciot** [jedelman8/nxos-ansible#79]
Hello,

Calling a common role defined as:

```
# roles/common/tasks/main.yml
- name: get NX-OS facts
  connection: local
  nxos_get_facts: host={{ inventory_hostname }} username={{ username }} password={{ password }} 
  tags: get-facts
```

leads to an exception:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1456510373.36-262320639696375/nxos_get_facts", line 2307, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1456510373.36-262320639696375/nxos_get_facts", line 316, in main
    detail)
NameError: **global name 'detail' is not defined**
fatal: [NX-OSv-Leaf-16]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_get_facts"}, "parsed": false}
```

Passing the argument as false (or true):

```
  nxos_get_facts: detail=false host={{ inventory_hostname }} username={{ username }} password={{ password }} 
```

leads to a fatal error:

```
fatal: [NX-OSv-Leaf-14]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"detail": "false", "host": "NX-OSv-Leaf-14", "password": "admin", "username": "admin"}, "module_name": "nxos_get_facts"}, "msg": "**unsupported parameter for module: detail**"}
```

**Comment by jean-christophe-manciot** [comment]
Same results if I call nxos_get_facts from within a "top level" playbook instead of a role:

```
# tmp-get-facts.yml
- name: get facts
  hosts: leaves-sf
  connection: local
  gather_facts: no

  tasks:

    - name: get NX-OS facts
      nxos_get_facts: host={{ inventory_hostname }} username={{ username }} password={{ password }}
      tags: get-facts

```

**Comment by jedelman8** [comment]
Funny, just fixed it.  Please do a pull and try again.

This works now:

```
tasks:

  - name: GET FACTS
    nxos_get_facts: host={{ inventory_hostname }} username={{ username
```

}} password={{ password }}

```
  - debug: var=nxos
```

**Comment by jean-christophe-manciot** [comment]
Thanks, yes, it works.
Now I have another issue when I try to save those facts locally which may or may not be related to your module. I have filed it on Ansible project, but so far no answer. Could you please take a look and tell me if you can reproduce it and whether or not you can fix it?
https://github.com/ansible/ansible/issues/14671

**Comment by jedelman8** [comment]
I'd recommend cleaning up your template to simplify troubelshooting, but
after a quick look two things:
- The recent changed introduced a new key called `nxos` that stores all
  facts.  So, in a template, you can do {{ nxos | to_nice_json }} to see all
  other key-value pairs; this also means to access other stuff like power
  supply information, you'd need to do {{ nxos.power_supply_info |
  to_nice_json }}
- Also, haven't tested this on Ansible 2.x yet.

**Comment by jean-christophe-manciot** [comment]
With a simpler templates/nx-os_facts.j2:
DEVICE: {{ inventory_hostname }}
NX-OS Facts:
{{ nxos | to_nice_json }}

I get the same error:

```
TASK [common : get NX-OS facts] ************************************************
ok: [NX-OSv-Spine-12]
ok: [NX-OSv-Spine-11]

TASK [common : save NX-OS facts locally] ***************************************
fatal: [NX-OSv-Spine-12]: FAILED! => {"changed": false, "failed": true, "msg": "ValueError: Circular reference detected"}
fatal: [NX-OSv-Spine-11]: FAILED! => {"changed": false, "failed": true, "msg": "ValueError: Circular reference detected"}

```

**Comment by jean-christophe-manciot** [comment]
I have found the issue: if I remove the first line (DEVICE: {{ inventory_hostname }}), the role gets executed correctly:

```
TASK [common : get NX-OS facts] ************************************************
ok: [NX-OSv-Spine-11]
ok: [NX-OSv-Spine-12]

TASK [common : save NX-OS facts locally] ***************************************
changed: [NX-OSv-Spine-11]
changed: [NX-OSv-Spine-12]
```
