### ISSUE TITLE
nxos_feature module call always returns an error with routing protocols

### ISSUE THREAD

**Issue by jean-christophe-manciot** [jedelman8/nxos-ansible#81]
No issue when used with all other features, but the errors occur with bgp, eigrp, isis, ospf or ospfv3:
For example, with **BGP**:

```
TASK [common : Enable features] ************************************************
task path: /media/actionmystique/SAMSUNG-Ext4-1/Labs/GNS3/CCNP-Cloud/CLDAUT/Distributed-Clouds/Ansible/roles/common/tasks/main.yml:38
ESTABLISH LOCAL CONNECTION FOR USER: root
NX-OSv-Spine-11 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384 `" )'
ESTABLISH LOCAL CONNECTION FOR USER: root
NX-OSv-Spine-12 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457456089.38-174671932266582 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457456089.38-174671932266582 `" )'
NX-OSv-Spine-11 PUT /tmp/tmpRezkR8 TO /root/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384/nxos_feature
NX-OSv-Spine-11 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384/nxos_feature; rm -rf "/root/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384/" > /dev/null 2>&1'
NX-OSv-Spine-12 PUT /tmp/tmp434aFF TO /root/.ansible/tmp/ansible-tmp-1457456089.38-174671932266582/nxos_feature
NX-OSv-Spine-12 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1457456089.38-174671932266582/nxos_feature; rm -rf "/root/.ansible/tmp/ansible-tmp-1457456089.38-174671932266582/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384/nxos_feature", line 2248, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1457456089.38-211358150843384/nxos_feature", line 272, in main
    device.config(cmds)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/device.py", line 138, in config
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature grace period is disabled. CLI execution error. Error Found on Command Number: 1

fatal: [NX-OSv-Spine-11]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_feature"}, "parsed": false}
```

With **OSPF**:

```
TASK [common : Enable features] ************************************************
task path: /media/actionmystique/SAMSUNG-Ext4-1/Labs/GNS3/CCNP-Cloud/CLDAUT/Distributed-Clouds/Ansible/roles/common/tasks/main.yml:38
ESTABLISH LOCAL CONNECTION FOR USER: root
NX-OSv-Spine-11 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900 `" )'
ESTABLISH LOCAL CONNECTION FOR USER: root
NX-OSv-Spine-12 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457456482.55-271389165943352 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457456482.55-271389165943352 `" )'
NX-OSv-Spine-11 PUT /tmp/tmpG32lew TO /root/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900/nxos_feature
NX-OSv-Spine-11 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900/nxos_feature; rm -rf "/root/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900/" > /dev/null 2>&1'
NX-OSv-Spine-12 PUT /tmp/tmpqJ2zYX TO /root/.ansible/tmp/ansible-tmp-1457456482.55-271389165943352/nxos_feature
NX-OSv-Spine-12 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1457456482.55-271389165943352/nxos_feature; rm -rf "/root/.ansible/tmp/ansible-tmp-1457456482.55-271389165943352/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900/nxos_feature", line 2248, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1457456482.55-242689849207900/nxos_feature", line 272, in main
    device.config(cmds)
  File "/usr/local/lib/python2.7/dist-packages/pycsco/nxos/device.py", line 138, in config
    raise clierror
pycsco.nxos.error.CLIError: NX-OS CLI Configuration Error
Feature grace period is disabled. CLI execution error. Error Found on Command Number: 1

fatal: [NX-OSv-Spine-11]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_feature"}, "parsed": false}
```

Except for BGP, all RPs are the only features which have multiple instances:

```
show feature
Feature Name         Instance State 
-------------------- -------- -----
bfd                  1        disabled
bfd_app              1        disabled
bgp                  1        disabled
bulkstat             1        disabled
cable-management     1        disabled
cts                  1        disabled
dhcp                 1        disabled
dot1x                1        disabled
eigrp                1        disabled
eigrp                2        disabled
eigrp                3        disabled
eigrp                4        disabled
eigrp                5        disabled
eigrp                6        disabled
eigrp                7        disabled
eigrp                8        disabled
eigrp                9        disabled
eigrp                10       disabled
eigrp                11       disabled
eigrp                12       disabled
eigrp                13       disabled
eigrp                14       disabled
eigrp                15       disabled
eigrp                16       disabled
elo                  1        disabled
eth_port_sec         1        disabled
evb                  1        disabled
evc                  1        disabled
evmed                1        disabled
fabric-access        1        disabled
fabric_mcast         1        disabled
glbp                 1        disabled
hmm                  1        disabled
hsrp_engine          1        disabled
imp                  1        disabled
interface-vlan       1        enabled
isis                 1        disabled
isis                 2        disabled
isis                 3        disabled
isis                 4        disabled
isis                 5        disabled
isis                 6        disabled
isis                 7        disabled
isis                 8        disabled
isis                 9        disabled
isis                 10       disabled
isis                 11       disabled
isis                 12       disabled
isis                 13       disabled
isis                 14       disabled
isis                 15       disabled
isis                 16       disabled
itd                  1        disabled
l2vpn                1        disabled
l3vpn                1        disabled
ldap                 1        disabled
ldp                  1        disabled
lisp                 1        disabled
lldp                 1        disabled
mpls_te              1        disabled
msdp                 1        disabled
msrp                 1        disabled
mvpn                 1        disabled
mvrp                 1        disabled
netflow              1        enabled
ngoam                1        disabled
nve                  1        disabled
nxapi                1        enabled
onep                 1        disabled
ospf                 1        disabled
ospf                 2        disabled
ospf                 3        disabled
ospf                 4        disabled
ospf                 5        disabled
ospf                 6        disabled
ospf                 7        disabled
ospf                 8        disabled
ospf                 9        disabled
ospf                 10       disabled
ospf                 11       disabled
ospf                 12       disabled
ospf                 13       disabled
ospf                 14       disabled
ospf                 15       disabled
ospf                 16       disabled
ospfv3               1        disabled
ospfv3               2        disabled
ospfv3               3        disabled
ospfv3               4        disabled
ospfv3               5        disabled
...
```

**Comment by jean-christophe-manciot** [comment]
Yoiu can dismiss this thread: just a license issue solved with a "grace period".
