### ISSUE TITLE
Running into error with examples-get_ipv4_interface.yml

### ISSUE THREAD

**Issue by Markos1922** [jedelman8/nxos-ansible#84]
Hi,
I am seeing the following error when running the script examples-get_ipv4_interface.yml on a nexus 9396 switch:

ESTABLISH LOCAL CONNECTION FOR USER: geko
nk1 EXEC /bin/sh -c '( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777`" )'
nk1 PUT /tmp/tmpJYOYG4 TO /root/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777/nxos_get_ipv4_interface
nk1 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/env python /root/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777/nxos_get_ipv4_interface; rm -rf "/root/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777/nxos_get_ipv4_interface", line 2086, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1461562801.15-4521970298777/nxos_get_ipv4_interface", line 120, in main
    get_data = nxapi_lib.get_ipv4_interface(device, interface)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/utils/nxapi_lib.py", line 713, in get_ipv4_interface
    data = device.show(command)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/device.py", line 111, in show
    data = self.sw1.send_req()
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/nxapi.py", line 287, in send_req
    return req.get_resp(self.req_to_string(), self.cookie, self.timeout)
  File "/usr/lib/python2.7/site-packages/pycsco/nxos/nxapi.py", line 141, in get_resp
    timeout=timeout)) as resp:
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(_args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized

fatal: [nk1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "nxos_get_ipv4_interface"}, "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @examples-get_ipv4_interface.retry

PLAY RECAP *********************************************************************
nk1                        : ok=0    changed=0    unreachable=0    failed=1   

The YML file looks as follows:

---
- name: get neighbors testing
  hosts: nk1
  connection: local
  gather_facts: no
  
  tasks:
  
    # retrieve ipv4 info for an interface (from 'show ip interface')
  -  nxos_get_ipv4_interface: interface=Ethernet2/1 host={{ inventory_hostname }}

Thanks 
GP

**Comment by jedelman8** [comment]
It's telling is unauthorized :)

Can you share your playbook? 

Please hard code your credentials using the username and password parameters for testing.

**Comment by jedelman8** [comment]
I'm on a computer now...test this:

```
nxos_get_ipv4_interface: interface=Ethernet2/1 host={{ inventory_hostname }} username=INSERT_YOUR_USERNAME password=YOURPASSWORD
```

**Comment by geepees2015** [comment]
Thanks Jason ! That worked. Is there a way of defining one time and calling it for each task ?

Appreciate your help.

GP
